language: go
go:
  - "1.23.4"
go_import_path: "github.com/Rammurthy5"

# Build and test the application
script:
  - make audit
  - make test
  - make build

# Deployment section
deploy:
  provider: releases
  api_key:
    secure: ""
  file: "bin/url-shortener"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - rammurthys@icloud.com
    on_success: always
    on_failure: always
