version: '3.8'
services:
  app:
    build: .
    ports:
      - "3200:3200"
    environment:
      - VIEWS_DIR=/app/internal/views
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${dbname}
    ports:
      - '${db_port}:${db_port}'
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: 'redis:4-alpine'
    command: redis-server --requirepass ${cache_password}
    ports:
      - '${cache_port}:${cache_port}'
    volumes:
      - redis-data:/data

volumes:
  postgres-db-volume:
  redis-data:
