env: ""
dev:
  http:
    port: "3200"
  db:
    host: ""
    port: ""
    username: ""
    password: ""
    dbname: ""
  cache:
    host: ""
    port: ""
    username: ""
    password: ""
    db: 0
test:
  http:
    port: "3201"
  db:
    host: ""
    port: ""
    username: ""
    password: ""
    dbname: ""
  cache:
    host: ""
    port: ""
    username: ""
    password: ""
    db: 0
prod:
  http:
    port: "3203"
  db:
    host: ""
    port: ""
    username: ""
    password: ""
    dbname: ""
  cache:
    host: ""
    port: ""
    username: ""
    password: ""
    db: 0